version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - factcheck-network

  backend:
    build:
      context: ./Back
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - factcheck-network

  frontend:
    build:
      context: ./Front/fact-check-clients
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - factcheck-network
    environment:
      - REACT_APP_API_URL=http://localhost:5000

networks:
  factcheck-network:
    driver: bridge
